/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juatsapp;

import implementaciones.ChatDAO;
import implementaciones.ConexionBD;
import entidades.Chat;
import entidades.Usuario;
import implementaciones.UsuarioDAO;
import interfaces.IChatsDAO;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.JTextPane;

/**
 *
 * @author Luis Baez
 */
public class FrmChat extends javax.swing.JFrame {

    /**
     * Creates new form FrmChat
     */
    Usuario usuario;
    DefaultListModel<String> model;
    FrmMuroChats muroChats;
    ConexionBD conexion;
    UsuarioDAO ud = new UsuarioDAO();
     
    public FrmChat(Usuario usuario,FrmMuroChats muroChats) {
        this.usuario=usuario;
        initComponents();
       model = new DefaultListModel<>();
ltIntegrantes.setModel(model);
this.muroChats=muroChats;
    }

    private FrmChat() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bCrear = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfIntegrantes = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ltIntegrantes = new javax.swing.JList<>();
        bAgregarIntegrante = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taChat = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        lblChat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear Chat");

        bCrear.setText("Crear");
        bCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Integrantes:");

        ltIntegrantes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ltIntegrantes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ltIntegrantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ltIntegrantesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ltIntegrantes);
        DefaultListModel<String> model = new DefaultListModel<>();
        ltIntegrantes.setModel(model);

        bAgregarIntegrante.setText("Agregar");
        bAgregarIntegrante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarIntegranteActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        taChat.setColumns(20);
        taChat.setRows(5);
        jScrollPane1.setViewportView(taChat);
        taChat.setWrapStyleWord(true);
        taChat.setLineWrap(true);

        jLabel2.setText("Lista de integrantes agregados:");

        lblChat.setText("Nombre del chat:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfIntegrantes)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(bAgregarIntegrante))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bCrear)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bCancelar))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(145, 145, 145))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblChat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(72, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChat))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfIntegrantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bAgregarIntegrante)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bCrear)
                    .addComponent(bCancelar))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearActionPerformed
        if (!taChat.getText().isEmpty()&&!model.isEmpty()) {
            Chat chat = new Chat(taChat.getText(), new Date(), usuario.getId());
           
//            List<Usuario> integrantes2 = new ArrayList<Usuario>();
            List<String> integrantes = new ArrayList<String>();
            for (int i = 0; i < model.getSize(); i++) {
                integrantes.add(model.get(i));
            }
            chat.setIntegrantes(integrantes);
            ChatDAO chatsDAO= new ChatDAO(); 
            chatsDAO.agregar(chat);
             JOptionPane.showMessageDialog(this, "Se ha creado chat", "Acción", INFORMATION_MESSAGE);
             muroChats.actualizarChats();
             muroChats.setVisible(true);
             this.dispose();
//            for (String tag : tags) {
//                System.out.println(tag);
//            }
        } else {
                JOptionPane.showMessageDialog(this, "Campos vacíos", "Error", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bCrearActionPerformed

    private void bAgregarIntegranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarIntegranteActionPerformed
        if (!tfIntegrantes.getText().isEmpty() && ud.buscarPorEmail(tfIntegrantes.getText()) != null && !tfIntegrantes.getText().equalsIgnoreCase(usuario.getEmailUsuario())) {
        model.addElement(tfIntegrantes.getText());    
        tfIntegrantes.setText(null);
        }else if (tfIntegrantes.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Llenar campo de texto con un usuario", "Error", ERROR_MESSAGE);
        }else if(ud.buscarPorEmail(tfIntegrantes.getText()) == null){
            JOptionPane.showMessageDialog(this, "El usuario no existe", "Error", ERROR_MESSAGE);
        }else if(tfIntegrantes.getText().equalsIgnoreCase(usuario.getEmailUsuario())){
            JOptionPane.showMessageDialog(this, "El usuario es el creador del grupo", "Error", ERROR_MESSAGE);
        }
            
        
    }//GEN-LAST:event_bAgregarIntegranteActionPerformed

    private void ltIntegrantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ltIntegrantesMouseClicked
      model.remove(ltIntegrantes.getSelectedIndex());
    }//GEN-LAST:event_ltIntegrantesMouseClicked

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmChat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregarIntegrante;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblChat;
    private javax.swing.JList<String> ltIntegrantes;
    private javax.swing.JTextArea taChat;
    private javax.swing.JTextField tfIntegrantes;
    // End of variables declaration//GEN-END:variables
}
