/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juatsapp;

import implementaciones.UsuarioDAO;
import implementaciones.ConexionBD;
import entidades.Usuario;
import interfaces.IUsuariosDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.OK_OPTION;

/**
 *
 * @author Luis Baez
 */
public class FrmCrearCuenta extends javax.swing.JFrame {

    ConexionBD conexion;
    /**
     * Creates new form FrmCrearCuenta
     */
    public FrmCrearCuenta() {
        initComponents();
    }

    public boolean verificarCampos() {
//        System.out.println(tfEmail.getText());
        String contra = String.copyValueOf(pfContra.getPassword());
        String contra2 = String.copyValueOf(pfContra2.getPassword());
//        boolean validarFecha = dcNac.getDate() != null;
        return !tfEmail.getText().isEmpty() && !tfEdad.getText().isEmpty()
//                && validarFecha
                && !contra.isEmpty() && !contra2.isEmpty();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bCrearCuenta = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        lblEmail = new javax.swing.JLabel();
        lblContra = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        lblContra2 = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        cbSexo = new javax.swing.JComboBox<>();
        lblEdad = new javax.swing.JLabel();
        tfEdad = new javax.swing.JTextField();
        pfContra = new javax.swing.JPasswordField();
        pfContra2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear cuenta");

        bCrearCuenta.setText("Crear cuenta");
        bCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearCuentaActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        lblEmail.setText("Correo electrónico");

        lblContra.setText("Contraseña:");

        lblContra2.setText("Confirmar contraseña:");

        lblSexo.setText("Sexo:");

        cbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer", "Robot" }));
        cbSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSexoActionPerformed(evt);
            }
        });

        lblEdad.setText("Edad:");

        tfEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEdadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEdad)
                            .addComponent(lblSexo)
                            .addComponent(lblContra2)
                            .addComponent(lblContra)
                            .addComponent(lblEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfEmail)
                            .addComponent(cbSexo, 0, 134, Short.MAX_VALUE)
                            .addComponent(tfEdad)
                            .addComponent(pfContra)
                            .addComponent(pfContra2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(bCrearCuenta)
                        .addGap(75, 75, 75)
                        .addComponent(bCancelar)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSexo)
                    .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEdad)
                    .addComponent(tfEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContra)
                    .addComponent(pfContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContra2)
                    .addComponent(pfContra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancelar)
                    .addComponent(bCrearCuenta))
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearCuentaActionPerformed

        if (verificarCampos()) {
            String contra = String.copyValueOf(pfContra.getPassword());
            String contra2 = String.copyValueOf(pfContra2.getPassword());
            if (contra.equals(contra2)) {
                UsuarioDAO ud = new UsuarioDAO();
                Usuario usuario;
                if (cbSexo.getSelectedItem().toString().equalsIgnoreCase("Hombre")) {
                    usuario = new Usuario(tfEmail.getText(), tfEdad.getText(), 'H', contra);
                } else if (cbSexo.getSelectedItem().toString().equalsIgnoreCase("Mujer")) {
                    usuario = new Usuario(tfEmail.getText(), tfEdad.getText(), 'M', contra);
                } else {
                    usuario = new Usuario(tfEmail.getText(), tfEdad.getText(), 'R', contra);
                        }

                //System.out.println(usuario.getContrasenia());
                if (ud.buscarPorEmail(usuario.getEmailUsuario()) == null) {
                    ud.agregar(usuario);
                    JOptionPane.showMessageDialog(this, "Se ha creado usuario", "Acción", INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Ya existe el usuario, cambiar el correo", "Error", ERROR_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden", "Error", ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Faltan campos", "Error", ERROR_MESSAGE);
        }

    }//GEN-LAST:event_bCrearCuentaActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        FrmIniciarSesion frm = new FrmIniciarSesion();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void tfEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEdadActionPerformed

    private void cbSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSexoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCrearCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bCrearCuenta;
    private javax.swing.JComboBox<String> cbSexo;
    private javax.swing.JLabel lblContra;
    private javax.swing.JLabel lblContra2;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JPasswordField pfContra;
    private javax.swing.JPasswordField pfContra2;
    private javax.swing.JTextField tfEdad;
    private javax.swing.JTextField tfEmail;
    // End of variables declaration//GEN-END:variables
}
