/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juatsapp;

import implementaciones.ChatDAO;
import implementaciones.ConexionBD;
import implementaciones.UsuarioDAO;
import interfaces.IChatsDAO;
import interfaces.IUsuariosDAO;
import entidades.Mensaje;
import entidades.Chat;
import entidades.Usuario;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;

/**
 *
 * @author Luis Baez
 */
public class PanelMensaje extends javax.swing.JPanel {

    /**
     * Creates new form PanelMensaje
     */
    Usuario usuarioConectado;
    Chat chat;
    Mensaje mensaje;
    FrmMuroChats muro;
    ConexionBD conexion;

    public PanelMensaje(Mensaje mensaje, Usuario usuarioConectado, Chat chat,FrmMuroChats muro) {
        initComponents();
        this.usuarioConectado = usuarioConectado;
        this.mensaje = mensaje;
        this.chat=chat;
        this.muro = muro;
        agregarContenido();
    }

    public void agregarContenido() {
        if (mensaje != null) {
            UsuarioDAO ud = new UsuarioDAO();
            Usuario autor = ud.buscarPorId(mensaje.getAutor());
            lbAutor.setText(autor.getEmailUsuario());
            SimpleDateFormat formato = new SimpleDateFormat("dd/MMM/yyyy HH:mm");
            String fecha = formato.format(mensaje.getFechaHora());
            lbFechaHora.setText(fecha);
//          

            taMensaje.append(mensaje.getMensaje());
//            if (usuarioConectado.getId().equals(mensaje.getAutor())) {
//                bEliminar.setVisible(true);
//                bEliminar.setEnabled(true);
//            } else {
//                bEliminar.setVisible(false);
//                bEliminar.setEnabled(false);
//            }
//        } else {
//            //System.out.println("kiuvo");
        }

//       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbAutor = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taMensaje = new javax.swing.JTextArea();
        lbFechaHora = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel1.setText("De:");

        lbAutor.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lbAutor.setText("jLabel2");

        jLabel3.setText("Enviado:");

        taMensaje.setEditable(false);
        taMensaje.setColumns(20);
        taMensaje.setRows(5);
        jScrollPane1.setViewportView(taMensaje);

        lbFechaHora.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbAutor))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbFechaHora)))
                        .addGap(31, 351, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbAutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbFechaHora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAutor;
    private javax.swing.JLabel lbFechaHora;
    private javax.swing.JTextArea taMensaje;
    // End of variables declaration//GEN-END:variables
}
