/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juatsapp;

import implementaciones.ChatDAO;
import implementaciones.UsuarioDAO;
import implementaciones.ConexionBD;
import interfaces.IChatsDAO;
import interfaces.IUsuariosDAO;
import entidades.Mensaje;
import entidades.Chat;
import entidades.Usuario;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;

/**
 *
 * @author Luis Baez
 */
public class PanelChat extends javax.swing.JPanel {

    /**
     * Creates new form PanelChat
     */
    Usuario usuarioConectado;
    Chat chat;
    FrmMuroChats muro;
    ConexionBD conexion;

    public PanelChat(Usuario usuarioConectado, Chat chat, FrmMuroChats muro) {
        initComponents();
        this.usuarioConectado = usuarioConectado;
        this.chat = chat;
        this.muro = muro;
        agregarContenido();
    }

    public void agregarContenido() {

        UsuarioDAO ud = new UsuarioDAO();
        Usuario autor = ud.buscarPorId(chat.getAutor());
        lbAutor.setText(autor.getEmailUsuario());
        SimpleDateFormat formato = new SimpleDateFormat("dd/MMM/yyyy HH:mm");
        String fecha = formato.format(chat.getFechaHora());        
        lbfecha.setText(fecha);
        Object[] integrantes = chat.getIntegrantes().toArray();

        String integrantesConvertidos = "";
        for (int i = 0; i < integrantes.length; i++) {
            if (i == integrantes.length - 1) {
                integrantesConvertidos += integrantes[i].toString();
            } else {
                integrantesConvertidos = integrantes[i] + ",";
            }
        }
        lbIntegrantes.setText(integrantesConvertidos);
//        taChat.append(chat.getTituloChat());
        lblTitulo.setText(chat.getTituloChat());
        if (usuarioConectado.getId().equals(chat.getAutor())) {
            bEliminar.setVisible(true);
            bEliminar.setEnabled(true);
        } else {
            bEliminar.setVisible(false);
            bEliminar.setEnabled(false);
        }

        if (!chat.getMensajes().isEmpty()) {
            agregarMensajes();
        }

    }

    public void agregarMensajes() {

        if (!chat.getMensajes().isEmpty()) {
            List<Mensaje> mensajes = chat.getMensajes();
            for (Mensaje mensaje : mensajes) {
                pMensajes.add(new PanelMensaje(mensaje, usuarioConectado,chat,muro));
            }
        } else {
            System.out.println("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lbAutor = new javax.swing.JLabel();
        lbfecha = new javax.swing.JLabel();
        bEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbIntegrantes = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pMensajes = new javax.swing.JPanel();
        lblMensajes = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bEnviarMnsj = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        tfMensaje = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbAutor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbAutor.setText("jLabel1");

        lbfecha.setText("jLabel2");

        bEliminar.setText("Eliminar Chat");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        jLabel1.setText("Integrantes:");

        lbIntegrantes.setText("jLabel2");

        pMensajes.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane2.setViewportView(pMensajes);

        lblMensajes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMensajes.setText("Mensajes:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Creador:");

        jLabel4.setText("Fecha de creación:");

        bEnviarMnsj.setText("Enviar");
        bEnviarMnsj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEnviarMnsjActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("jLabel2");

        tfMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMensajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(lbfecha))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbAutor))
                            .addComponent(lblTitulo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbIntegrantes)
                        .addGap(55, 55, 55)
                        .addComponent(bEliminar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMensajes)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bEnviarMnsj)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lbIntegrantes)
                            .addComponent(bEliminar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lbAutor))
                        .addGap(5, 5, 5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbfecha)
                    .addComponent(jLabel4))
                .addGap(13, 13, 13)
                .addComponent(lblMensajes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bEnviarMnsj))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bEnviarMnsjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnviarMnsjActionPerformed
//        FrmMensaje frm = new FrmMensaje(chat, usuarioConectado,muro);
//        frm.setLocationRelativeTo(this);
//        frm.setVisible(true);
        if (!tfMensaje.getText().isEmpty()) {
            Mensaje mensaje = new Mensaje(tfMensaje.getText(), new Date(), usuarioConectado.getId());
            chat.agregarMensaje(mensaje);
            ChatDAO pd = new ChatDAO();
            pd.actualizar(chat);
//            JOptionPane.showMessageDialog(this, "Has enviado un mensaje", "Acción", INFORMATION_MESSAGE);
            muro.actualizarChats();
            muro.setVisible(true);
//            this.dispose();

        } else {
            JOptionPane.showMessageDialog(this, "Campo vacío", "Error", ERROR_MESSAGE);
        }

    }//GEN-LAST:event_bEnviarMnsjActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(this, "¿Estás segur@ que quieres borrarlo?", "Atención", YES_NO_OPTION, QUESTION_MESSAGE);
        if (opcion == 0) {
            //     System.out.println(opcion);
            ChatDAO pd = new ChatDAO();
            pd.eliminar(chat.getId());
            muro.actualizarChats();
            JOptionPane.showMessageDialog(this, "Has borrado tu chat", "Acción", INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_bEliminarActionPerformed

    private void tfMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMensajeActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_tfMensajeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bEnviarMnsj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbAutor;
    private javax.swing.JLabel lbIntegrantes;
    private javax.swing.JLabel lbfecha;
    private javax.swing.JLabel lblMensajes;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pMensajes;
    private javax.swing.JTextField tfMensaje;
    // End of variables declaration//GEN-END:variables
}
